### ISSUE TITLE
most informative parts of error messages are unavailable with `last_error` and only through `last_trace()`

### ISSUE THREAD

**Issue by AltfunsMA** [r-lib/rlang#1023]
I assume there are technical reasons for having to call `rlang::last_error`, but it would be helpful for `rlang` to present straight away the line in the script where the error is suspected to have originated.

In the example below, the line reported by `last_trace` was perfectly accurate. Even showing `map_lgl` would help quickly confirm the root of the problem;  but `last_error` did not report either. Is it not possible to make `last_error` report the most useful parts of that call hierarchy?

Thanks for making this amazing package!

![image](https://user-images.githubusercontent.com/26325512/87040827-a2954180-c234-11ea-9117-746657ec730e.png)

**Comment by lionel-** [comment]
hmm yes, perhaps it makes sense to show all the top level siblings.

**Comment by lionel-** [comment]
On second thought, it would be confusing to show sibling nodes in that flat representation. But see `?rlang_backtrace_on_error`, that's a global option that allows you to display full backtraces by default.

In this particular case the error trace would be much improved with a change to purrr. The `stop_` calls should be evaluated in the environments of `map_` calls so that they are part of the same branch. I'll open a purrr issue.
