### ISSUE TITLE
Feature Request: Comments in new_function()

### ISSUE THREAD

**Issue by MyKo101** [r-lib/rlang#1040]
This feature request is to add in the ability to insert comments into a function that has been created by the `new_function()` function.

Within Base R, if a function factory has comments inside it's resulting function, these comments are passed on to output function:
```
f_factory <- function(x){
  function(t){
    #This is a comment
    x + t
  }
```

However, there does not seem to be a way to replicate this behaviour within `new_function()`. The closest I've got is to create a dummy function that `glue`s a string into itself.

```
`#` <- function(.x) invisible(expr(`#`(!!stringr::str_glue(.x,.envir=caller_env()))))

f_factory <- function(x){
  new_function(
    pairlist2(t=),
    expr({
      !!`#`("x is equal to {x}")
      x+t
    })
  )
}

f <- f_factory(1)
```
the function `f()` now looks like this:
```
function (t) 
{
    `#`("x is equal to 1")
    x + t
}
<environment: 0x000001e0facf1df8>
```
This works since outputs from `#` are invisible and don't get saved anywhere but isn't quite the same and this certainly isn't a comment. (The `glue`-ing of the string wouldn't be necessary, but it would certainly be useful)

**Comment by lionel-** [comment]
The easiest way to do it is to parse the function from a string. When you see comments in a function, that's because the whole textual source has been saved by the parser and stored in the function in a field called a "source reference". This is used for debugging and other things.

It would be nice for rlang to have utilities to forge source references, but this is currently out of scope.
