### ISSUE TITLE
Transformation rules in rlang?

### ISSUE THREAD

**Issue by ramiromagno** [r-lib/rlang#1044]
I am sorry if GitHub issues is not really the place to ask questions but here it goes:

Have you ever thought of including functionality similar to Wolfram's tranformation rules?

https://reference.wolfram.com/language/tutorial/TransformationRulesAndDefinitions.html#18035

Would this even make sense in the context of the metaprogramming provided by rlang?

Something like:

```R
expr(x^2) %/.%
  c(x = expr(1+y)) %/.%
  c(y = expr(b))

#> (1+b)^2
```

**Comment by lionel-** [comment]
There's currently no plan for including substitution in rlang.

You can get most of the way there using `substitute()`:

```r
`%/.%` <- function(x, y) {
  eval(substitute(substitute(x, y), list(x = x)))
}

expr(x^2) %/.%
  c(x = expr(1 + y)) %/.%
  c(y = expr(b))
#> (1 + b)^2
```

The issue is that `substitute()` zaps attributes. For example formulas and quosures will lose their attributes and class:

```r
class(
  quo(x^2) %/.%
    c(x = expr(1 + y)) %/.%
    c(y = expr(b))
)
#> [1] "call"
```

The `%./%` implementation using `substitute()` is a bit tricky, IIRC it is explained in adv-r. You can do the same thing with rlang:

```r
`%/.%` <- function(x, y) {
  eval(expr(substitute(!!x, !!y)))
}
```
