### ISSUE TITLE
make hash() a generic

### ISSUE THREAD

**Issue by topepo** [r-lib/rlang#1080]
We want to apply this to various tidymodel objects (like resamples). The hashing might only occur on some select columns and rows of the object (if it is a tibble). See tidymodels/rsample#201 as an example. 

Rather than coming up with new function names, it would be better to have methods for `hash()`.

**Comment by lionel-** [comment]
I think if `hash()` were to become generic, it should be a recursive generic so that `hash(x)` and `hash(list(x))` have similar behaviour. I'm thinking about writing our own extensible SEXP traversal routine, which should make it possible to implement this sort of behaviour.

There should also be a non-OO variant. Perhaps `hash()` would become generic and the current hash function would become `hash0()`.

**Comment by lionel-** [comment]
This is currently out of scope for `hash()` given the technical difficulties.
