### ISSUE TITLE
Support glue in `abort()`

### ISSUE THREAD

**Issue by lionel-** [r-lib/rlang#1090]

**Comment by lionel-** [comment]
@hadley I think the main problem is how do we find the correct environment when `abort()` is wrapped? I guess we would need to use `glue()` explicitly at each wrapper level:

```r
my_function <- function(bar) {
  abort("foo {bar}")
}

my_function <- function(bar) {
  stop_bar("foo {bar}")
}
stop_bar <- function(msg) {
  abort(glue(msg, envir = caller_env())
}
```

**Comment by tzakharko** [comment]
@lionel- What you could do (although not sure how robust it is) is chase down the argument promise until you get a character constant. A quick and dirty non-optimal implementation: 

```c
SEXP glue_constant_arg(SEXP call, SEXP op, SEXP args, SEXP rho) { 
  // the sole argument is the argument name
  SEXP name = CADR(args);
  if(TYPEOF(name) != SYMSXP) error("name must be a symbol");

  SEXP maybe_promise = Rf_findVarInFrame(rho, name);
  // chase the unevaluated promise down the symbol chain until we get to a value
  while(
    TYPEOF(maybe_promise) == PROMSXP && 
    PRENV(maybe_promise) != R_NilValue &&
    TYPEOF(PREXPR(maybe_promise)) == SYMSXP
  ) {
    maybe_promise = Rf_findVarInFrame(PRENV(maybe_promise), PREXPR(maybe_promise));  
  }

  // bail out unless it's an unevaluated promise that holds a character const
  if( 
    TYPEOF(maybe_promise) != PROMSXP ||
    PRENV(maybe_promise) == R_NilValue ||
    TYPEOF(PREXPR(maybe_promise)) != STRSXP
  ) {
    // evaluate it in case it's a promise
    return Rf_eval(maybe_promise, R_EmptyEnv);
  }

  // we have found our character constant, pass it to glue
  SEXP glue_call = PROTECT(
    lang3(install("glue"), 
    maybe_promise, 
    PRENV(maybe_promise))
  );
  SET_TAG(CDDR(glue_call), install(".envir")); 
  UNPROTECT(1);

  return Rf_eval(glue_call, rho);
} 
```

and then

```R
f <- function(msg) {
  .External2("glue_constant_arg", sym("msg"))
}

g <- function(x) {
  f(x)
}

local({
  x <- 15
  g("hello {x}")
})
```

Few problems with this approach:
 - it will only work if the argument is forwarded without being used in any way (the promise is unevaluated)
 - it cannot distinguish between constants passed via arguments and constants in lazy bindings  (I suppose one can work around this by checking the symbol against function formals, but is it worth the hassle?)

**Comment by lionel-** [comment]
@tzakharko This will not work reliably because the compiler unwraps constants from promises. We can't capture the environment of a string.

**Comment by tzakharko** [comment]
Ah, I see, that's a bummer. I think one could still walk around it by adding call stack examination, but that could also break in the future if compile behavior changes...

**Comment by hadley** [comment]
@lionel- I think it would be fine to add an explicit `.env` argument for this case. I think it's pretty unusual in our workflow.

**Comment by jennybc** [comment]
Because I've wrapped `abort()` a few times recently, I'll link to those as real-world examples.

https://github.com/r-lib/gargle/blob/342ac042403fd1d6b47a2ee8a80bcbd9e1978712/R/conditions.R#L10-L16

https://github.com/tidyverse/googlesheets4/blob/95a9af501ab64d4ee97bed211d23f99f7b6cd848/R/conditions.R#L10-L14

I do it to use `glue()` and to add a class. @Hadley says we [sort of decided adding such a class is not that important / mildly discouraged](https://github.com/r-lib/rlang/pull/1144#issuecomment-812194232)? Although I don't really remember this 🤔 the package-specific error class is probably not that useful for googlesheets4, but probably is useful for a package like gargle. So if `abort()` supported `glue()`, most of my wrappers would become unnecessary.

If I wrap my own wrapper to create a specific type of error, my rule is that the condition message and data must derive from the arguments passed in. So I don't pass an environment down.

https://github.com/r-lib/gargle/blob/342ac042403fd1d6b47a2ee8a80bcbd9e1978712/R/conditions.R#L43-L50

https://github.com/tidyverse/googlesheets4/blob/95a9af501ab64d4ee97bed211d23f99f7b6cd848/R/conditions.R#L26-L34
