### ISSUE TITLE
Why isn't it cnd_catch()?

### ISSUE THREAD

**Issue by jennybc** [r-lib/rlang#1104]
It feels like `catch_cnd()` should be `cnd_catch()`.

**Comment by lionel-** [comment]
That is because `cnd` is not a namespace but a suffix indicating the return
type. If used as a prefix it would wrongly suggest an input type. See also
`error_cnd()`. Also `parse_expr()` vs `expr_deparse()`.

This naming strategy used in rlang, purrr, and vctrs is at odds with the
namespacing strategy of features related by a theme that seems to inform
your intuition. There is no ideal reconciliation of the two approaches.

**Comment by jennybc** [comment]
I see. Yeah I definitely use the "theme" mentality to find functions sometimes and more than once I've tripped over this with `catch_cnd()`.
