### ISSUE TITLE
Confusing behaviour of is_missing() when an argument has a default

### ISSUE THREAD

**Issue by joeroe** [r-lib/rlang#1106]
The documentation for is_missing() says that it is "like base::missing() but also supports testing for missing arguments contained in other objects like lists". I therefore expected these functions to be equivalent, but they're not:

```r
base_missing <- function(x = 1) {
  missing(x)
}

rlang_missing <- function(x = 1) {
  rlang::is_missing(x)
}

base_missing()
#> [1] TRUE
rlang_missing()
#> [1] FALSE
```

Probably I'm just misunderstanding the purpose of is_missing(), but perhaps the documentation could be updated to clarify that this is another way it differs from base::missing()?

**Comment by aalucaci** [comment]
Hi,
I think you don't compare the same thing in the 2 cases. If you look at the definition of `rlang::is_missing`, you'll see it calls `base::is_missing` (it does a bit more, but that's not important for this comparison). The thing is, since your example function have default arguments, the argument is not really missing... not sure how to express this. Please see my examples below: if you nest the `base::is_missing` one frame more, as `rlang::is_missing` does it, you'll see that both base and rlang give the same results:

`
base_missing <- function(x = 1) {
  message("x: ", x)
  missing(x)
}
base_missing() # TRUE

###############################
missing_0 <- function(x) {
  message("x: ", x)
  missing(x)
}
base_missing_deep <- function(x = 1) {
  message("x: ", x)
  missing_0(x)
}
base_missing_deep() # FALSE

###############################
rlang_missing <- function(x = 1) {
  rlang::is_missing(x)
}
rlang_missing() # FALSE
`
I would say this has little to do with rlang, but with the way R handles default arguments.

Just my 2 cents,
Angela

**Comment by joeroe** [comment]
Thank you for the additional information @aalucaci. I do understand *why* the behaviour is different, which is why I opened this as a documentation issue rather than a bug. The `missing()` documentation warns that it does not work reliably if nested in another function. You could debate whether arguments with a default are really "missing". IMO it is a useful feature that `missing()` treats them this way, e.g. when you want to override a default value but only if the user hasn't confirmed they want it. 

But more to the point, the documentation for `missing()` makes it obvious that this is the expected behaviour: "missing can be used to test whether a value was *specified as an argument* to a function." The documentation for `is_missing()` implies that it behaves in the same was as `missing()` just with added support for missing arguments contained inside other objects. I'm suggesting that it should make it clearer that it doesn't behave the same way in this instance.

However since you've pointed me to the source for `is_missing()` and I see it is just a very thin wrapper around `missing()`, I wonder if this might be a bug after all? Was it intended that arguments with defaults should be considered non-missing regardless of the user input?

**Comment by lionel-** [comment]
I agree this is a bug. The problem is that it's difficult to implement a variant of `missing()` without circumventing the public R API. I'll try to find a solution.
