### ISSUE TITLE
Provide helper for checking arguments are provided

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#1118]
e.g.

```R
f <- function(foo) {
  check_present(foo)
}
f()
#> Error: `contact` must be suppled in call to `f()`
```

vs

```R
f <- function(foo) {
  foo
}
f()
#> Error in f() : argument "foo" is missing, with no default
```

This is especially useful if the argument is not evaluated by the current function, but another function called by the current function, and it's more informative than just forcing arguments at the start of the function.

cc @wch

**Comment by wch** [comment]
A little context: using `force()` is considered to be the idiomatic way of evaluating arguments early, but the resulting error messages are unhelpful because they don't tell the user which function is calling `force()`:

```R
f <- function(foo) {
  force(foo)
}
f()
#> Error in force(foo): argument "foo" is missing, with no default
```

Using the bare variable results in better error messages and has less overhead, but it does not convey intent (unless we were to start using that as a convention).

In the particular case that started this discussion, it would be useful to have a function that would check multiple arguments, as in:

```R
check_present(x, y, z)
```

It could also be useful to have a function that checks all arguments without having to name them:

```R
check_present_all()
```

One more thing to consider: there is a difference between checking for missingness, and evaluating an expression. In most of the cases I can think of, there's no drawback to doing both, so it would be simpler to have a single function that does both, but there are some cases where you would just want to check for missingness without evaluating the expression.

**Comment by lionel-** [comment]
In general we hide the throwing context in error messages. I wonder if we can find some guidelines to decide when it's better to include it and how. In this particular use case I see these two properties:

- The error is most likely directly caused by an end user (as opposed to a programming error deep in the stack)
- The function called by the user should be mentioned, not the function at the throw site

**Comment by lionel-** [comment]
This could be `arg_require()` for consistency with `arg_match()` and the error message could be

```r
#> Error: `my_function()` requires `foo` to be supplied.
```

This seems clear and simple.

@wch I'd prefer not taking dots for consistency with other functions. Also functions typically have very few arguments without a default so there is less of a need to make the check less verbose.
