### ISSUE TITLE
Rsession.exe Error: Entry Point Not Found for R_RemoveVarFromFrame - rlang.dll

### ISSUE THREAD

**Issue by sarahjean0659** [r-lib/rlang#1132]
I am working on R 3.6.3 and RStudio 1.2.5042. Please note that I'm working within a closed network, so I have to manually find and download the packages that I require for R. I am also not able to update my R package without going through a process with our IT department.

I am working within R Studio and the project requires rlang 0.4.10 (previously had version rlang 0.2.1 and had no issues). I downloaded it and placed it in the appropriate library replacing the old version (Documents > R > win-library > 3.6). I closed and reopened R Studio. 

When opening R Studio, I get the following error: "Rsession.exe Entry Point Not Found. The procedure entry point R_RemoveVarFromFrame could not be located in the dynamic link library." Then is points to the folder where rlang.dll is found.  (rlang > libs > x64 > rlang.dll).

To double shoot this error, I tested this on my home network (connected and able to update via install_packages()), and rlang 0.4.10 WORKS on R 3.6.3 and R Studio 1.2.5033.

I have done a lot of searching on google and other sites, and they all point to it being a R version problem. What I don't understand, is why it works on my home network with the same R version and not at my work station (closed network).

Please note that I have updated versions for multiple packages needed for rlang on the closed work network, and that did not fix the issue.

Any solution would be greatly appreciated as this is holding up progress and I have hit a roadblock on finding a solution myself.

**Comment by lionel-** [comment]
> What I don't understand, is why it works on my home network with the same R version and not at my work station (closed network).

This is because the rlang package installed on your home computer was _compiled_ against an older R version (probably 3.6) whereas the one at your work station was compiled against a newer version (probably 4.0).

Binary packages compiled with a recent R are not guaranteed to work with an older R. (On the other hand it's usually fine to use a binary compiled against an older R on a newer R.)

The solution is to build rlang yourself or use an older binary. On Windows, CRAN provides binaries for the current release as well as the previous release, called `oldrel`. You can find the `.zip` at https://cran.r-project.org/web/packages/rlang/index.html, in this case https://cran.r-project.org/bin/windows/contrib/3.6/rlang_0.4.10.zip.
