### ISSUE TITLE
Custom error class in check_installed()?

### ISSUE THREAD

**Issue by wlandau** [r-lib/rlang#1168]
Would you be open to a `class` argument for `check_installed()`. An example motivating use case is https://github.com/ropensci/targets/pull/331.

**Comment by lionel-** [comment]
I don't think so. First I'm not convinced by the use case for the following reasons:

- Testing the is-installed code paths is generally not worth the effort
- Adding error classes just for unit tests seems bad practice because an error class is user-facing and becomes part of the public API.

Also a `class` argument in `check_installed()` would be strange and distracting. The proper way to reclass an error is to rethrow it, which implies adding an error class to the API. As it happens, we plan to do this as part of #1150.
