### ISSUE TITLE
`abort()` auto bullet behavior has changed in dev rlang

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/rlang#1254]
CRAN rlang:

``` r
library(rlang)

abort(c("x", "y"))
#> Error: x
#> * y
```

dev rlang:

``` r
library(rlang)

abort(c("x", "y"))
#> Error: x
#> y
```

The CRAN version used to use this function on `message`, which auto-bulleted everything after `message[[1]]`, but that seems to have disappeared

```r
> rlang:::collapse_cnd_message
function (x) 
{
    if (length(x) > 1L) {
        paste(x[[1]], format_error_bullets(x[-1]), sep = "\n")
    }
    else {
        x
    }
}
```

This appeared in a dplyr snapshot test

**Comment by lionel-** [comment]
The change is on purpose to make the syntax consistent with cli. Bullets must now be explicit, e.g. `c("Header", "*" = "Bullet.")`

We have compatibility behaviour for unnamed vectors in `format_error_bullets()` but I'm not sure we want this in `abort()` because it would lock us in the old behaviour. The breaking change is relatively harmless but it would be nice to fix in dplyr before releasing rlang.

cc @romainfrancois

**Comment by lionel-** [comment]
> but it would be nice to fix in dplyr before releasing rlang.

Though that would be hard because `"*"` is not a valid name in CRAN rlang.
