### ISSUE TITLE
How to extract human-readable output from as.character(rlang_error)? 

### ISSUE THREAD

**Issue by MatthieuStigler** [r-lib/rlang#1366]
I am interested in extracting the simplest form of an `rlang_error`, using `as.character()`. By simplest I mean the essence of the error message, without the crayon/cli formatting,  that is the typical current output from `as.character(rlang_error)` such as: _\033[1m\033[33mError\033[39m in \033[38;5;255m`dplyr::select()`\033[39m:\033[22m\n\033[33m!\033[39m Can't subset columns that don't exist.\n\033[31mx\033[39m Column `x` doesn't exist.\n_,  I would like just to have _Can't subset columns that don't exist.\n Column `x` doesn't exist._

I was wondering whether:

- Is it possible to pass the argument `prefix` of `rlang::cnd_message()` into `as.character.rlang_error` ?
- Is it possible to add a new argument removing the remaining crayon/cli formatting?

Thanks!

```
a <- purrr:::safely(\(x) dplyr::select(iris, x))(none)
as.character(a$error)
```

will give: _"\033[1m\033[33mError\033[39m in \033[38;5;255m`dplyr::select()`\033[39m:\033[22m\n\033[33m!\033[39m object 'none' not found\n"_

**Comment by lionel-** [comment]
To disable colours you can write a helper function that calls `cnd_message()` or `as.character()` within `with_options(crayon.enabled = FALSE, *expr*)`.

As usual the problem with adding an argument is finding the right argument name and right interface. Ideally it would be consistent with the corresponding global option. On that front, `crayon.enabled` is technically superseded by `cli.num_colors`. However the latter is a bit technical, the values it takes are not obvious (you supply `1` to disable colours), and it suffers from spelling ambiguity.

I think a user-facing argument should take a boolean not a number of colours. Regarding the name, even though the crayon package is superseded, "crayon" has name recognition so `crayon = c(TRUE, FALSE)` might still be a good choice. Otherwise, `cli_colours = c(TRUE, FALSE)` might work. 

cc @gaborcsardi @hadley.

**Comment by gaborcsardi** [comment]
You can call `cli::ansi_strip()` to remove the ANSI sequences from the message.

**Comment by MatthieuStigler** [comment]
Thanks for the rapid answer and explanations @lionel- and @gaborcsardi 

I understand the difficulty of adding the  ansi stripping due to dependencies, and for my own case I'll just use `cli::ansi_strip()`, and some regexp to remove the visual `!` or `x` generated by the error message. Simple code for discoverability:

``` r
library(tidyverse)

a <- purrr:::safely(\(x) dplyr::select(iris, x))(none)

rlang::cnd_message(a$error, prefix = TRUE) |>cli::ansi_strip()
#> [1] "Error in `dplyr::select()`:\n! Can't subset columns that don't exist.\nx Column `x` doesn't exist."
rlang::cnd_message(a$error, prefix = FALSE) |>cli::ansi_strip()
#> [1] "Can't subset columns that don't exist.\nx Column `x` doesn't exist."
withr::with_options(list(crayon.enabled = FALSE), rlang::cnd_message(a$error, prefix = FALSE))
#> [1] "Can't subset columns that don't exist.\nx Column `x` doesn't exist."
```

New question: should the `x` and `!` not be considered as parts of the crayon output? Without crayon they seem to make less sense?

Thanks!

**Comment by lionel-** [comment]
I think we'll keep the `!` and `x` for simplicity and consistency.

**Comment by hadley** [comment]
I don't see any need for changes here.

**Comment by MatthieuStigler** [comment]
This makes sense, thanks everyone for the help!
