### ISSUE TITLE
env_binding_are_active evaluates active bindings twice

### ISSUE THREAD

**Issue by MilesMcBain** [r-lib/rlang#1376]
Probably unexpected, and prevents this function from being used over `bindingIsActive`. 

In `rlang` 1.0.2:

``` r
f <- local( {
    x <- 1
    function(v) {
       if (missing(v))
           cat("get\n")
       else {
           cat("set\n")
           x <<- v
       }
       x
    }
})
makeActiveBinding("fred", f, .GlobalEnv)
rlang::env_binding_are_active(.GlobalEnv, "fred")
#> get
#> get
#> fred 
#> TRUE
```

<sup>Created on 2022-03-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by MilesMcBain** [comment]
For clarity: evaluation should probably not occur at all, let alone twice :)

**Comment by DavisVaughan** [comment]
This seems to be because `Rf_findVarInFrame3()`, used by `r_env_find()` [here](), triggers active bindings. https://github.com/r-lib/rlang/blob/a768b4b25e1a0a54c3e171f373f090efdbd60060/src/rlang/env.h#L46

**Comment by DavisVaughan** [comment]
It seems to be a feature of `Rf_findVarInFrame3()` to trigger active bindings.

So maybe we can just reverse the order here, look for active bindings first, then promises (because checking for promises would have triggered the active bindings) https://github.com/r-lib/rlang/blob/6ed751bd70b02b02c67b2ee38cdf2ad00a12ea4b/src/rlang/env-binding.c#L23-L29
