### ISSUE TITLE
getting error: Must extract column with a single valid subscript. x Subscript `var` has size 25 but must be size 1.

### ISSUE THREAD

**Issue by Nikhil-malle** [r-lib/rlang#1395]
iphone_det_amz <- separate(iphone_det_amz,
                           col = iphone_det_amz$Name,
                           into = c("Storage","Color"),
                           sep = " ")

**Comment by lionel-** [comment]
Hello,

This looks like a user error rather than a bug in package (which is what github issues are for). This is probably from the tidyr package.

I would try posting your issue in a user forum like Stackoverflow or community.rstudio.com. Make sure to include a reproducible example (see https://reprex.tidyverse.org/). Otherwise no one will be able to help you.
