### ISSUE TITLE
friendly_type() and matrices

### ISSUE THREAD

**Issue by krlmlr** [r-lib/rlang#141]
For tidyverse/tibble#250, we want to throw a descriptive error if a matrix is passed, but:

``` r
rlang::friendly_type(rlang::type_of(diag(5)))
#> [1] "a double vector"
```

Any suggestions?

CC @hadley.

**Comment by lionel-** [comment]
hmm the issue is that matrices and arrays are kind of a compound type. I'm not sure we want `type_of()` to take into account dimensions.

Maybe it should return a character vector instead of a string, and `switch_type()` etc would take the first element. The other elements would still be available when they matter.

**Comment by lionel-** [comment]
or store that information in an attribute?

**Comment by hadley** [comment]
Could just check the length of `dims()` and pick from vector/matrix/array.  

@lionel- it seems reasonable to me to handle the dims attribute specially here

**Comment by lionel-** [comment]
shouldn't `type_of()` also return information about the underlying vector type?

**Comment by lionel-** [comment]
e.g. a matrix of lists is quite different than a matrix of integers

**Comment by lionel-** [comment]
or:

- `type_of()` returns one of "atomic", "list", "matrix", "array"
- `vec_type_of()` returns one of "logical", "integer", etc, "list"

it seems like one way or the other `friendly_type()` will have to take the original object as well (it now only takes the type).

**Comment by krlmlr** [comment]
I like the idea of having `type_of()` return a string with attributes.
