### ISSUE TITLE
Should we include one extra frame in traceback for "internal" errors

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#1410]
Not sure if this is well founded or possible, but I just hit this error:

```
── Error (test-vignettes.R:46:3): extra files copied and removed ───────────────
Error: 'inform' is not an exported object from 'namespace:cli'
Backtrace:
 1. base::suppressMessages(build_vignettes(pkg, quiet = TRUE))
      at test-vignettes.R:46:2
 3. devtools::build_vignettes(pkg, quiet = TRUE)
 4. devtools::copy_vignettes(pkg, keep_md)
      at devtools/R/vignettes.R:67:2
```

The problem is that none of the srcrefs in backtrace point to the line with the actual problem:

```R
  cli::inform(c(i = "Copying extra files {.file {path_file(extra_files)}} to {.path doc/}"))
```

It'd be really nice if we could add:

```
 5. cli::inform(c(i = "Copying extra files {.file {path_file(extra_files)}} to {.path doc/}"))
      at devtools/R/vignettes.R:39:2
```

**Comment by lionel-** [comment]
I think this will be hard because the call that contains the relevant srcref info is the one that executes the calling handler, and which we discard from backtraces to avoid multiple problems (calls irrelevant to users, the parent is globalenv so that doesn't interact well with showing only the trailing branch of the trace tree).

```r
calls <- NULL

withCallingHandlers(
  error = function(cnd) {
    calls <<- sys.calls()
  },
  with_srcref("
    1 + 1
    foobar()
  ")
)

calls[[7]]
#> foobar()

unstructure(calls[[7]])
#> .handleSimpleError(function(cnd) {
#>     calls <<- sys.calls()
#>   }, "could not find function \"foobar\"", base::quote(foobar()))
```

In theory there is no frame on the stack to which the source location could be attached. I'm not sure why the handler call gets decorated with this srcref.

**Comment by lionel-** [comment]
Sorry this seems too hard to implement. rlang is not given enough information because the error happens during evaluation of `{` outside of any relevant closure frame (the function is looked up before the frame is created).
