### ISSUE TITLE
Warning: replacing previous import 'data.table:::=' by 'rlang:::=' when loading 'myPackage' 

### ISSUE THREAD

**Issue by gwd666** [r-lib/rlang#1453]
I am developing a package that has some Imports/Dependencies among which there are also `rlang` and `data.table`. 
Lately when running `devtools::document()` I keep getting that warning in this issues subject - is ist safe to ignore or could/will this interfere with function calls like `data.table[ , SomeColumns := .. ]` ? 
Frankly I am not able to identify the place in my code that gives `devtools::document()` the idea to do this replacement - since I am not using  `rlang:::=` anywhere in my code, as opposed to `data.table:::=`, which I do use in one or two places.

**Comment by gwd666** [comment]
ok found the import that started causing this - interestingly with quite a delay ... but it was in utils-tidy-eval.R that got added by my `usethis::tidy_eval()` call

**Comment by caparks2** [comment]
I have the same issue. I'm unable to pass the R CMD check because of it. What did you end up doing to solve the problem? Or are you just living with it? I added the below to a "utils-data.table.R" file I made in the R folder, but I imagine it's not a great solution since `:=` is needed for updating by reference in `data.table`:
```r
#' @rawNamespace import(data.table, except = `:=`)
NULL
```
This wasn't great because I'm using `dtplyr` in my package, which doesn't seem to like being used without having the `data.table` namespace attached, including `data.table:::=`. An alternative idea is to delete the `:=` walrus from these lines in  "utils-tidy-eval.R".
```r
#' @importFrom rlang enquo enquos .data := as_name as_label
#' @aliases enquo enquos .data as_name := as_label
#' @export enquo enquos .data as_name := as_label
```
Either way it can't be good since both `data.table` and `rlang` depend on the walrus.

**Comment by markfairbanks** [comment]
You can import either the `data.table` version or the `rlang` version of `:=` and your package will work just fine for both use cases. As long as they're available in the namespace each package will interpret it correctly for its use.

This is how I built out `tidytable` (a package with the same idea as `dtplyr`) and I haven't run into any issues with CRAN or with package usability.

In my case I imported the `data.table` version and excluded the `rlang` version, and the `rlang` use cases still work correctly.

Here's the relevant file: https://github.com/markfairbanks/tidytable/blob/main/R/tidytable-package.R

**Comment by caparks2** [comment]
@markfairbanks thanks for making that clear! Good to see how you did it for `tidytable`.
