### ISSUE TITLE
eval_tidy with the magrittr pipe not using default env argument

### ISSUE THREAD

**Issue by KZARCA** [r-lib/rlang#1455]
`eval_tidy` has the default env argument set to `caller_env()`. However, when using the pipe, another environment is used.

```r
library(magrittr)
library(rlang)
#> 
#> Attaching package: 'rlang'
#> The following object is masked from 'package:magrittr':
#> 
#>     set_names
foo <- function(...){
  dots <- exprs(...)
  print(eval_tidy(dots[[1]], env = caller_env())) # OK
  print(eval_tidy(dots[[1]])) # Error
}
mean(1:5) %>% foo()
#> [1] 3
#> Error in eval_tidy(dots[[1]]): object '.' not found
```

**Comment by lionel-** [comment]
This is the expected behaviour. `eval()` and `eval_tidy()` both evaluate in the current environment. In general, you should only evaluate in the caller environment if you are sure the expression comes from there. In the case of `...`, that's not necessarily the case because dots can be forwarded from functions to functions.

You could use `enquos()` instead of `enexprs()` to capture the environments of the dots expressions. This would fix the example posted here. I recommend not supplying `env = caller_env()` and keep the default as a rule of thumb (it depends on the case though).
