### ISSUE TITLE
`abort()` strips linebreaks if `use_cli_format = TRUE`

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/rlang#1535]
Cf. https://github.com/r-lib/cli/issues/559. This might be by design, IDK:

```
❯ rlang::abort("foo\nbar", use_cli_format=FALSE)
Error:
! foo
bar
Run `rlang::last_error()` to see where the error occurred.

❯ rlang::abort("foo\nbar", use_cli_format=TRUE)
Error:
! foo bar
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by lionel-** [comment]
I haven't looked closely, but isn't this expected cli behaviour?

```r
writeLines(cli::format_error("foo\nbar"))
#> foo bar
```

**Comment by gaborcsardi** [comment]
But why does `rlang:abort()` call cli? `cli::cli_error()` already formats the output, no? 

So we have:

```r
❯ cli::format_inline("foo\fbar")
[1] "foo\nbar"

❯ rlang::abort(cli::format_inline("foo\fbar"))
Error:
! foo
bar
Run `rlang::last_error()` to see where the error occurred.

❯ rlang::abort(cli::format_inline("foo\fbar"), use_cli_format=TRUE)
Error:
! foo bar
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by lionel-** [comment]
This is how we designed it:

- When `use_cli_format` is `FALSE`, bullets are formatted using rlang's fallback (which does not fully implement cli's behaviour).

- When `use_cli_format` is `TRUE`, either because set directly, or because the calling context has `local_use_cli()` active, then we format bullets using cli with full paragraph wrapping etc.

- `cli_abort()` formats the inline markups and interpolates, then call `abort()`, which then calls cli to format the bullets and error layout.

Maybe the problem comes from `cli::format_inline()`? I remember I was surprised to see it doesn't preserve newlines, which is what I expected based on the design above.

**Comment by lionel-** [comment]
Worth noting that bullet/layout formatting is called at display time in this design, not at throw time. For instance the width might have changed in between.

**Comment by gaborcsardi** [comment]
> Maybe the problem comes from cli::format_inline()? I remember I was surprised to see it doesn't preserve newlines, which is what I expected based on the design above.

I can modify it to keep newlines if that works better with `rlang::abort()`.

**Comment by gaborcsardi** [comment]
> I can modify it to keep newlines if that works better with rlang::abort().

That does not seem to change anything, though:

```r
❯ cli::format_inline("foo\nbar")
[1] "foo\nbar"

❯ cli::cli_abort("foo\nbar")
Error:
! foo bar
Run `rlang::last_error()` to see where the error occurred.

❯ cli::cli_abort("foo\fbar")
Error:
! foo bar
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by lionel-** [comment]
Can you push your changes to a branch and link here please? I'll take a look next week.

**Comment by gaborcsardi** [comment]
https://github.com/r-lib/cli/tree/fix/format-inline-keep-newline

Thanks!

**Comment by gaborcsardi** [comment]
I added a parameter to keep or drop newlines. I'll try to make `keep_newlines = TRUE` the default, if no revdeps are broken.

**Comment by lionel-** [comment]
Fixed by https://github.com/r-lib/cli/commit/a7c63c249348dae10b2484ad06f5e1ca9f9a2d28

I'm keeping this open so I don't forget to add a unit test for this.
