### ISSUE TITLE
is_numeric(), is_scalar_numeric()

### ISSUE THREAD

**Issue by egnha** [r-lib/rlang#182]
Among the predicates, `is_bare_numeric()` is available, but `is_numeric()` and `is_scalar_numeric()` are not. Are these omissions intentional? (Have I overlooked a good reason to include only one of the three?)

**Comment by egnha** [comment]
I see now that commit b304ef1cb6820f4492a720c9d908dbc1b38e1f9f replaced `is_numeric()` by `is_integerish()`. But I don't see how `is_integerish()` subsumes `is_numeric()`, in functionality, since `is_integerish()` is stricter.

**Comment by lionel-** [comment]
That's because `numeric` is a _concept_, so `is_numeric()` should have been a generic entry point. E.g. a factor is not numeric though it's interegish. We didn't want to tackle broad genericity of that kind in rlang, so we came up with the narrower concept of integerish that is only defined on base types.

**Comment by egnha** [comment]
Thanks for clarifying the difference.

Since “numeric” is not a type, but `c("double", "integer")` is regarded as a kind of “composite type” by `is_bare_numeric()`, would it make sense to rename that function to `is_bare_numerical()`? (i.e., “numerical“ stands for the composite type.) If so, then companion predicates `is_numerical()` and `is_scalar_numerical()` might also be appropriate.

**Comment by lionel-** [comment]
That might make sense.

**Comment by lionel-** [comment]
I think the concept of integerish is the best fitting for rlang.
