### ISSUE TITLE
set_attrs() API

### ISSUE THREAD

**Issue by lionel-** [r-lib/rlang#257]
I think `set_attrs()` should not update part of the attributes, it should update the attributes as a whole. Then `add_attrs()` would be used to update the attributes. Maybe also have `poke_attrs()` and `push_attrs()` variants that would change the attributes in place. This generally only makes sense in C code but it's nice to be able to prototype with R.

Same for `set_class()` vs `add_class()`.

Maybe it'd also makes sense to have some kind of "matcher" argument for `add_` and `push_` functions? Or/and offset?

**Comment by krlmlr** [comment]
The `row.names` attribute is a constant source of headaches in tibble:

- Even querying it is an expensive operation, because in some situations it will create a character vector of length `nrow(x)` 
- Extra care must be taken during updates

Because `rlang::set_attrs()` currently seems to update attributes as a whole, I can't use it for tibble. Just my two cents, no immediate action needed -- I've worked around: tidyverse/tibble@6e538db194b8.

**Comment by lionel-** [comment]
I think it makes more sense to have dedicated getters and setters for this kind of attributes. Likewise, the C level equivalent of `getAttrib()` in rlang should never do any kind of allocation, e.g. it shouldn't generate a names vectors when asked the names attribute of pairlists and language objects. Instead they should have their own primitives for collecting the tags.

**Comment by lionel-** [comment]
`set_attrs()` and co are now in questioning stage. Maybe we should just add a `structure2()` as a light wrapper around `structure()` with `!!!` support. On the other hand with `bang()` and `exec()` this kind of wrappers are not really needed. Closing for now.

**Comment by vspinu** [comment]
What can we use instead of `set_attrs` which is now deprecated? I cannot find anything in the docs.

**Comment by lionel-** [comment]
I just use `structure()` nowadays, with `blast()` when I need splicing.

**Comment by vspinu** [comment]
I see. I like the clean semantics of the `set_xyz` naming though. What about `mut_attribs`? 

`blast()` is not exported btw.
