### ISSUE TITLE
Should `call_node` convert to symbol when CAR is a string?

### ISSUE THREAD

**Issue by vspinu** [r-lib/rlang#377]
Tiny aesthetic issue: 

```R
> call_node("foo", pairlist(a = 34))
"foo"(a = 34)
```

It would be nice if string CARs were automatically converted to symbols.

**Comment by lionel-** [comment]
This function is now `new_call()`. But I don't think it should preprocess inputs because this API is for prototyping C code. This is also why the node accessors and setters don't type-check their inputs and might crash R if the surrounding code does not ensure correct types. Since this API is dangerous, it is marked as internal.
