### ISSUE TITLE
Add quosure methods for operators

### ISSUE THREAD

**Issue by lionel-** [r-lib/rlang#478]
To fail appropriately when omitting to unquote, c.f. https://github.com/tidyverse/dplyr/issues/3476#issuecomment-378890913

Once we're able to return typed expressions from `expr()` / `enexpr()` etc, would be a good idea to implement the method as well.

cc @romainfrancois

**Comment by lionel-** [comment]
What do you mean?

**Comment by romainfrancois** [comment]
Yeah sorry that was not clear at all. 

There's two things I guess: 
- defining the s3 methods on quosure objects, so that independently of their implementation we would be protected from the original problem 
- investigate why things like this happen in R in the first place, does it make sense, and if not should we negotiate to fix it

```{r}
> f <- ~x
> f > 2
[1] FALSE
> f < 2
[1] TRUE
```

**Comment by lionel-** [comment]
Expressions are deparsed for comparison. I think it should be forbidden but that probably won't happen. R core people likely won't find this to be a big issue and they will prefer not to risk breaking code.
