### ISSUE TITLE
Branch selection in calltrace / adding a calltrace to an error

### ISSUE THREAD

**Issue by jimhester** [r-lib/rlang#485]
For use in testthat, but could be used elsewhere as well

```r
add_calltrace <- function(code) {
  withCallingHandlers(code,
    error = function(e) {
      x <- calltrace()

      # Find second-to-last tree
      # Last tree is handleSimpleError etc
      toplevel <- which(x$parents == 0)
      n <- length(toplevel)
      start <- toplevel[n - 1]
      end <- toplevel[n] - 1

      throw(conditionMessage(e), trace = x[start:end])
    }
  )
}
```

cc @hadley

**Comment by hadley** [comment]
At least need to expose low-level way to get (e.g.) 2nd to last tree

**Comment by lionel-** [comment]
Thanks! I used the same implementation but with `err$message` rather than `conditionMessage()`. I think the latter should only be used at print-time since it might contain automatically generated output based on information that might be changed (such as rlang backtrails).

I think it's a bit early to expose low-level ways of trimming backtraces because it's a bit messy at the moment (for instance the strategy above doesn't work for trimming capturing contexts as they are part of the backtrail rather than a sibling branch).
