### ISSUE TITLE
Consider renaming backtrail

### ISSUE THREAD

**Issue by jimhester** [r-lib/rlang#605]
backtrail has colloquial usage [[1]] as

> backtrail (plural backtrails): 
> 1. A small path or trail that is not used regularly.

These concepts are pretty universally called backtraces or tracebacks in computing. 

Introducing a new term is confusing, even if the tree structure makes it slightly different than a traditional backtrace. Most users aren't interested in the difference, or looking up what a backtrail is, they just want to figure out where their code failed.

[1]: https://en.wiktionary.org/wiki/backtrail

**Comment by lionel-** [comment]
Good point, it's probably not that confusing to call simplified and full backtraces by the same name. Should it be `print(trace, simplify = "branch")` then, Instead of `simplify = "trail"`?

How about simplifying to branch by default in the print method, and have the str method print the full backtrace:

```r
rlang::backtrace()       # Backtrace branch of last error
str(rlang::backtrace())  # Full backtrace of last error
```

(`backtrace()` just returns `.Last.error` which is then auto-printed)

**Comment by jimhester** [comment]
That sounds pretty good to me!

**Comment by lionel-** [comment]
This is now `summary(rlang::last_error())` to get the full backtrace.
