### ISSUE TITLE
is_bool()

### ISSUE THREAD

**Issue by lionel-** [r-lib/rlang#695]
Like `is_string()`, for checking inputs:

```r
is_bool <- function(x) {
  is_logical(x, n = 1) && !is.na(x)
}
```

**Comment by lionel-** [comment]
And `is_number()`

```r
is_number <- function(x) {
  is_integerish(x, n = 1, finite = TRUE)
}
```

**Comment by s-fleck** [comment]
Just my 2c: I would go `is_bool()` for an arbitrary length 2-value-logic vector and `is_scalar_bool()` for a vector of length 1 for consistency. I also often define an `is_n()` function which checks for positive, non-`NA` integerishs (as in **n**atural numbers). This is something one often actually wants when doing an argument check for scalar integerishs.

**Comment by s-fleck** [comment]
hmm.. from the name I would assume `is_length()` to be something like as `function(x, y) length(x) == y`. 

I commented on this issue because I am already using a function `is_bool()`/`is_scalar_bool()` across my packages, though i have to confess I almost exclusively need the scalar version (as you have pointed out). 

Still it would be more consistent with other rlang predicates. When `is_integer()` checks for an integer vector, why does `is_bool()` not check for a boolean vector? There is also `is.flag()` in assertthat (which is basically `is_scalar_logical()`), but that is also not really optimal in my oppionion :/

**Comment by lionel-** [comment]
>  from the name I would assume is_length() to be something like as function(x, y) length(x) == y.

Good point.

> why does is_bool() not check for a boolean vector?

Because those are called logical vectors. I don't think `is_bool()` would be a consistent name for checking logical vectors. But it is consistent with `is_string()` / `is_character()`.

**Comment by s-fleck** [comment]
oh sorry I meant `is_bool()` for true (2 valued/non-na) boolean vectors as opposed to `is_logical()` . though I'm not sure how often you really need those in practice

**Comment by DavisVaughan** [comment]
+1 for is_bool(), as this would definitely come in handy when type checking some argument inputs!
