### ISSUE TITLE
Function to show last traceback

### ISSUE THREAD

**Issue by hadley** [r-lib/rlang#700]
i.e. just the "backtrace" part of `summary(rlang::last_error())`

**Comment by lionel-** [comment]
`last_trace()`?

**Comment by hadley** [comment]
:+1:

**Comment by hadley** [comment]
And it should probably have `simplify` argument

**Comment by lionel-** [comment]
I was thinking it would just return a trace and then you can do

```r
print(last_trace(), simplify = "collapse")
```

Should traces print in full by default? I'm now wondering whether simplify = collapse is really useful.

**Comment by hadley** [comment]
An additional call to print is annoying, IMO.

**Comment by lionel-** [comment]
I think with the right default it won't be annoying. Do you need to collapse often?

**Comment by lionel-** [comment]
Otherwise `last_trace()` needs to print the trace in addition to returning it, or store a parameter in the trace structure that would overwrite the print arguments. This doesn't seem right. With `simplify = "none"` as default, the additional call to print should be rare enough that it won't be annoying. Unless I'm missing something?

**Comment by hadley** [comment]
You could add it as an attribute. It just feels common enough to me that it'll be helpful.  But defaulting to "none" will probably resolve most of my unhappiness.

**Comment by lionel-** [comment]
ok, let's try out `last_trace()` with the new default. Let me know if it would still be useful to add the argument.
