### ISSUE TITLE
is_integerish doesn't handle NA values consistently

### ISSUE THREAD

**Issue by s-fleck** [r-lib/rlang#751]
`is_integerish()` handles `NA` values differently depending on whether they are integers or doubles.

I think the following both lines of code should both return the same value:
```
> rlang::is_integerish(NA)
[1] FALSE
> rlang::is_integerish(NA_integer_)
[1] TRUE
```

**Comment by lionel-** [comment]
Agreed, though note that `NA` is not a double but a logical (try `typeof(NA)`).

**Comment by s-fleck** [comment]
right, my bad
```
> rlang::is_integerish(NA_real_)
[1] TRUE
```
So that behavior for those is consistent. `TRUE` is not what I would have expected, but I guess there is no "right" decision here.

**Comment by lionel-** [comment]
In general we are now considering `NA` as having unspecified type, so it makes sense to convert it to `na_int` here.

**Comment by lionel-** [comment]
Sorry, I have reverted this because it caused issues downstream. I think the semantics of rlang are clearer if it deals exclusively with base types, rather than conceptual types. So you'll need to special case for `NA`. Maybe we could have a conceptual vctrs type for integer numbers (or it could be implemented in a package) to solve this problem, though it's not high priority.
