### ISSUE TITLE
Enable arguments of the form "pkg::fun" in 'as_function()'

### ISSUE THREAD

**Issue by paulponcet** [r-lib/rlang#775]
While `rlang::as_function("median")` works perfectly fine, `rlang::as_function("stats::median")` returns an error. 

    Error in get(x, envir = env, mode = "function") :
      object 'stats::median' of mode 'function' was not found

Would it be possible that `as_function()` accept arguments of that latter form, as does the function `as.fun()` in package [bazar](https://cran.rstudio.com/web/packages/bazar/index.html)?

**Comment by lionel-** [comment]
I wouldn't rely on passing functions as strings. There is no information about where to find the function in a string, so that creates brittle interfaces. We might even remove this in the future. While your suggestion does bring this information in the case of package functions, I see no advantage passing `"foo::bar"` instead of `foo::bar`.
