### ISSUE TITLE
`frame_position()` soft-deprecated, use `trace_back()` ? 

### ISSUE THREAD

**Issue by moodymudskipper** [r-lib/rlang#780]
`frame_position()` is soft deprecated and the help says : 

> These functions are soft-deprecated and replaced by trace_back().

I don't understand however how to use `trace_back()` to get the frame position.

How can I get the following output using `trace_back()` rather than `frame_position()` ?

```
fun1 <- function(){
  env <- parent.frame()
  rlang::frame_position(env)
}
fun1()
#> Warning: `frame_position()` is soft-deprecated as of rlang 0.3.0.
#> This warning is displayed once per session.
#> [1] 0

fun2 <- function() fun1()
fun2()
#> [1] 1
```

**Comment by lionel-** [comment]
The functionality isn't completely subsumed by `trace_back()`. These functions are being removed from rlang because we don't need them for internal purposes and we are discouraging idioms based on stack introspection.

It would make sense to extract the deprecated frame and context function in their own package. We won't do it because of finite maintenance resources, but anyone is welcome create this package :)

**Comment by moodymudskipper** [comment]
Got it thanks.

For whoever might care, here's a poor man's `frame_position` that works for my use case.

```
frame_pos <- function(frame) {
  pos <- which(sapply(sys.frames(), identical, frame))
  if(!length(pos)) pos <- 0
  pos
}
```

output :

```
fun1 <- function(){
  env <- parent.frame()
  frame_pos(env)
}
fun1()
#> [1] 0

fun2 <- function() fun1()
fun2()
#> [1] 1
```
