### ISSUE TITLE
Suggestion: Preserve expression names in `parse_exprs()`

### ISSUE THREAD

**Issue by ArtemSokolov** [r-lib/rlang#808]
This is a very minor suggestion, but the current behavior of `parse_exprs` does not preserve expression names if given a named string vector.

``` r
x <- parse_exprs( c(e1="a+b", e2="a*10") )
# [[1]]
# a + b
#
# [[2]]
# a * 10
```

The desired behavior can be emulated via `purrr::map()` as
``` r
y <- purrr::map( c(e1="a+b", e2="a*10"), parse_expr )
# $e1
# a + b
# 
# $e2
# a * 10
```

The motivation for this is to help streamline downstream usage in `dplyr` verbs. For example,

``` r
tibble( a=1:3, b=4:6 ) %>% mutate( !!!y )
# # A tibble: 3 x 4
#       a     b    e1    e2
#   <int> <int> <int> <dbl>
# 1     1     4     5    10
# 2     2     5     7    20
# 3     3     6     9    30
```
produces columns with desired names `e1` and `e2`, whereas the equivalent `mutate( !!!x )` doesn't.

**Comment by lionel-** [comment]
I think this makes sense.

**Comment by zeehio** [comment]
(For context, this issue was opened from https://stackoverflow.com/a/56937482/446149 )

Preserving names in `parse_exprs` presents a potential problem: When the text to be parsed contains more than one expression, using `parse_expr` gives an error:

``` r
rlang::parse_expr("a+b;c+d")
#> More than one expression parsed
```

However `parse_exprs` returns all the expressions in a list, and that list can be longer than the input, for instance:

``` r
rlang::parse_exprs(c("bar;foo", "car"))
#> [[1]]
#> bar
#> 
#> [[2]]
#> foo
#> 
#> [[3]]
#> car
```

This is mentioned in the man page:

```
     ‘parse_expr()’ returns an expression, ‘parse_exprs()’ returns a
     list of expressions. Note that for the plural variants the length
     of the output may be greater than the length of the input. This
     would happen is one of the strings contain several expressions
     (such as ‘"foo; bar"’).
```

Using purrr::map + parse_expr has the advantage that it will give an error if any of the given strings contains more than one expression (such as ‘"foo; bar"’).

Naming the output of `parse_exprs` with the names of its input would give the impression that `parse_exprs` gives always an output of the same length than the input.

The names `parse_expr` and `parse_exprs` led me to think that the second one is a vectorized version of the first, but as it is mentioned in the documentation that is not generally true.

Maybe `parse_exprs` could get a `keep_names` argument. 
- If `keep_names = TRUE`, then `parse_exprs` behaves as `purrr::map + parse_expr`, raising an error if multiple expressions are passed "bar;foo"
- If `keep_names = FALSE`, then `parse_exprs` behaves as it is behaving now, returning an unnamed list that can be longer than the input.

**Comment by ArtemSokolov** [comment]
Thanks for pointing this out, Sergio.

Another potential implementation would be to only keep names for single-expression strings and issue a warning for others. For example, it might look like this:
``` r
parse_exprs( c(e1="a+b; b+c", e2="a*10") )
# [[1]]
# a + b
# 
# [[2]]
# b + c
# 
# e2
# a * 10
# Warning: more than one expression parsed for e1; name not preserved
```

But having an extra `keep_names` argument controlling the behavior is a good idea too!

**Comment by lionel-** [comment]
I have chosen to recycle the names, this way they can be matched to the expressions.

If you want to enforce one expression per string, you can use `map(x, parse_expr)`.
