### ISSUE TITLE
Name repair in quos() / enquos()

### ISSUE THREAD

**Issue by romainfrancois** [r-lib/rlang#810]
Originally in: https://github.com/tidyverse/dplyr/issues/4484

``` r
library(rlang)

fun <- function(...) {
  names(enquos(..., .named = TRUE))
}
fun(
  ifelse(status == "tropical depression", paste(year, month, day, sep = "-"), paste(year, month, sep = "-")),
  ifelse(status == "tropical storm", paste(day, month, year, sep = "-"), paste(month, year, sep = "-"))
)
#> [1] "ifelse(...)" "ifelse(...)"
```

**Comment by lionel-** [comment]
This is complicated because we don't want to export `vec_as_names()` from rlang.

We could have the name repair engine in rlang, exported as C callable, but then it will become harder to develop new features in `vctrs::vec_as_names()`.

Alternatively we could add vctrs in `Suggests:`, pick up name repair callables at runtime, and throw an error when vctrs is not installed. I think that might be best.

cc @hadley

**Comment by hadley** [comment]
We could say that `enquos()` doesn't do name repair, and you should use vctrs if needed.

**Comment by romainfrancois** [comment]
That's fine, the initial example in https://github.com/tidyverse/dplyr/issues/4484 is a bit of a stretch anyway.
