### ISSUE TITLE
Minimum requirements are not enough for tests to pass

### ISSUE THREAD

**Issue by QuLogic** [r-lib/rlang#855]
When building against an older system, some tests fail:
```
  1. Error: error is printed with backtrace (@test-cnd-abort.R#80)
  2. Error: parent errors are not displayed in error message and backtrace (@test-cnd-abort.R#113)
  3. Error: backtrace reminder is displayed when called from `last_error()` (@test-cnd-abort.R#135)
  4. Error: capture context doesn't leak into low-level backtraces (@test-cnd-abort.R#178)
  5. Error: can use conditionMessage() method in subclasses of rlang errors (@test-cnd-error.R#22)
  6. Error: rlang_error.print() calls conditionMessage() method (@test-cnd-error.R#46)
```
Comparing to a system that does work, the differences seem to be:
```patch

+backports 1.1.5
+ellipsis 0.3.0
-htmltools 0.3.6
+htmltools 0.4.0
-pillar 1.3.1
+pillar 1.4.2
-testthat 2.0.1
+testthat 2.2.1
+vctrs 0.2.0
+zeallot 0.1.0
```
I'm not sure if it's new pillar or new testthat that is required. This is new with 0.4.1, I believe, as well.

**Comment by lionel-** [comment]
yeah, unfortunately it is hard to keep track of minimal dep versions. The alternative is to just set the minimal version to whatever I have on my computer at the time of releasing. This shouldn't cause problems as long as this isn't making the package inadvertently depend on a newer R version (which shouldn't be the case because we're careful about a consistent minimal R version in our packages).

I would guess this is about testthat? If you can find exactly why this fails, I will update the dep.

**Comment by lionel-** [comment]
Thank you. Dev rlang is going to depend on the new testthat once it's on CRAN, so I'll update the dependency then.
