### ISSUE TITLE
Last error is not being retained in a knitr context

### ISSUE THREAD

**Issue by jennybc** [r-lib/rlang#894]
Save this as "knitr-woes.Rmd" and then render. I think something regressed between rlang v0.4.0 and v0.4.1.

---

````
---
output: html_document
---

Let's make sure rlang remembers the last error in a knitr context.

```{r error = TRUE}
packageVersion("rlang")
rlang::abort("abort!")
rlang::last_error()
```
````

---

Then render it. Currently I see:

```
Let’s make sure rlang remembers the last error in a knitr context.

    packageVersion("rlang")

    ## [1] '0.4.2'

    rlang::abort("abort!")

    ## Error: abort!

    rlang::last_error()

    ## Error: Can't show last error because no error was recorded yet
```

Relates to https://github.com/hadley/adv-r/issues/1592, https://github.com/tidyverse/reprex/pull/306

**Comment by lionel-** [comment]
I think this will have to be fixed in `evaluate::evaluate()` by setting the `rlang_force_unhandled_error` option.

**Comment by jennybc** [comment]
😢 but evaluate hasn't changed since May 2019. Is there not another route back to getting rlang traces in knitr?

**Comment by jennybc** [comment]
Now I see there's an explanation elsewhere, so I will wait and see ...

**Comment by lionel-** [comment]
Copying the explanation here:

> That's because we have moved the capture logic from `conditionMessage()` to `signalCondition()`. If the error is handled, we don't add reminder nor save the error.
> 
> There's an escape hatch that `evaluate::evaluate()` could use, I'll look into it.

It's not as easy as I thought because setting the option mentioned above would cause all errors to be saved, including those that are actually handled, e.g. `try(abort("foo"))`.

However it may be a close enough approximation, for the purpose of generating knitted documents. I can't see any big downside. What do you think @gaborcsardi and @hadley?

**Comment by lionel-** [comment]
There's probably no need to change evaluate actually, since individual documents can set `rlang_force_unhandled_error`.

@jennybc It probably makes sense for reprex to set the option? That might be a good way to find out if there are any big downsides to the approach. `rlang_backtrace_on_error` might also be useful in reprex, perhaps this trio:

```r
options(
  rlang_force_unhandled_error = TRUE,
  rlang_backtrace_on_error = "full",
  rlang_trace_top_env = environment()
)
```

**Comment by lionel-** [comment]
Now I see that setting `rlang_force_unhandled_error` definitely has a big downside unless `rlang_backtrace_on_error` is set to `"none"`. When set to something else, it causes all caught errors to include the reminder/trace in their `message` field. This option was really designed for unit tests.

**Comment by gaborcsardi** [comment]
I think ideally we would change evaluate, but for now forcing the backtrace seems fine.

**Comment by jennybc** [comment]
Using the suggestions above, I have gotten rlang errors / traces back in reprex. That won't do anything for knitr / bookdown more generally (e.g. https://github.com/hadley/adv-r/issues/1592). I'll leave it to others to decide if it makes sense to pursue this any further elsewhere.
